# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    footer_service:
        class: AdminBundle\Service\FooterService
        arguments: ['@form.factory', '@doctrine', '@session', '@service_container']
        
    media_listener:
        class: AdminBundle\Service\MediaListenerService
        arguments: ['@kernel']
        tags:
            - { name: kernel.event_subscriber }
