# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    key_value_form:
        class: AdminBundle\Service\KeyValueFormService
        arguments: ['@form.factory', '@doctrine', '@session', '@service_container']

    media_listener:
        class: AdminBundle\Service\MediaListenerService
        arguments: ['@liip_imagine.controller', '@liip_imagine.filter.configuration']
        tags:
            - { name: kernel.event_subscriber }
            
    serialization_listener:
        class: AdminBundle\Service\SerializationListenerService
        arguments: ['@liip_imagine.cache.manager']
        tags:
            - { name: jms_serializer.event_subscriber }

    entity_manager:
        class: AdminBundle\Service\EntityManagerService
        arguments: ['@doctrine']
