<?php

namespace AdminBundle\Repository;

/**
 * FooterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeyValueRepository extends \Doctrine\ORM\EntityRepository
{
}
