<?php
/**
 * Written by Michał Turemka <michal.turemka@gmail.com>
 */

namespace BlogBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * SubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberRepository extends EntityRepository
{
}
